[package]
name = "dezero"
version = "0.1.0"
authors = ["matonix <automatonix@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.3"
num-traits = "0.2.14"